
package aplikacja;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Mateusz
 */
public class Menu extends javax.swing.JFrame {

    
    public Menu() {
        initComponents();   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacja");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jButton4.setText("Dodaj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Imie");

        jLabel9.setText("Nazwisko");

        jLabel10.setText("Województwo");

        jLabel11.setText("Miasto");

        jLabel12.setText("Ulica");

        jLabel13.setText("Data zatrudnienia");

        jButton2.setText("Usuń wybrany wiersz");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel28.setText("Stawka nominalna");

        jButton13.setText("Aktualizuj wiersz");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton4))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton13))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kierowcy", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton3.setText("Dodaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Marka");

        jLabel2.setText("Numer rejestracyjny");

        jLabel4.setText("Model");

        jLabel3.setText("Numer VIN");

        jLabel5.setText("Ubezpieczenie");

        jLabel6.setText("Badanie techniczne");

        jLabel7.setText("Kierowca");

        jButton1.setText("Usuń wybrany wiersz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton14.setText("Aktualizuj wybrany wiersz");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128)
                                        .addComponent(jButton3))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)
                        .addComponent(jButton14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pojazdy", jPanel1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jButton6.setText("Dodaj");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setText("Nazwa trasy");

        jLabel21.setText("Czas trasy");

        jLabel22.setText("Długość trasy");

        jButton10.setText("Usuń wybrany wiersz");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton15.setText("Aktualizuj wybrany wiersz");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton15))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(323, 323, 323)
                                .addComponent(jButton10)))
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel20)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jButton15))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Trasy", jPanel4);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jButton7.setText("Dodaj");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel23.setText("Punkt");

        jLabel24.setText("Odległość od poprzedniego punktu");

        jLabel25.setText("Czas przejazdu od poprzedniego punktu");

        jLabel26.setText("ID_trasy");

        jButton9.setText("Usuń wybrany wiersz");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton16.setText("Aktualizuj wybrany wiersz");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 495, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextField22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)))
                        .addGap(20, 20, 20))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 68, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Punkty pośrednie", jPanel5);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jButton5.setText("Dodaj");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel14.setText("ID_kierowcy");

        jLabel15.setText("Data rozpoczęcia kursu");

        jLabel16.setText("Data zakończenia kursu");

        jLabel17.setText("Stan licznika początek");

        jLabel18.setText("Stan licznika koniec");

        jLabel19.setText("ID_trasy");

        jButton8.setText("Usuń wybrany wiersz");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton17.setText("Aktualizuj wybrany wiersz");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(16, 16, 16)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jTextField12))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jTextField15)
                            .addComponent(jTextField17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17))
                .addGap(0, 59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kursy", jPanel3);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Spersonalizowane zapytanie", "Kierowcy i ich pojazdy", "Kursy kierowców", "Rzeczywista odleglosc,czas i śr prędkość", "Zarobki pracowników" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList1);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable6);

        jButton11.setText("Zapisz raport do pliku");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Wyświetl raport");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("select * from pojazdy");
        jScrollPane3.setViewportView(jTextArea1);

        jLabel27.setText("Spersonalizowane zapytanie do bazy");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButton12)
                        .addGap(218, 218, 218)
                        .addComponent(jButton11))
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(101, 101, 101))
        );

        jTabbedPane1.addTab("Raporty", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void odswież_tab()
    {
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL = "Select * from Pojazdy";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        
        try {
            String SQL = "Select * from Kierowcy";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            String SQL = "Select * from Kursy";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
         try {
            String SQL = "Select * from Trasy";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        try {
            String SQL = "Select * from [Punkty pośrednie]";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        
        String nic="";
        jTextField1.setText(nic);
        jTextField2.setText(nic);
        jTextField3.setText(nic);
        jTextField4.setText(nic);
        jTextField5.setText(nic);
        jTextField6.setText(nic);
        
        jTextField7.setText(nic);
        jTextField8.setText(nic);
        jTextField9.setText(nic);
        jTextField10.setText(nic);
        jTextField11.setText(nic);
        jTextField12.setText(nic);
        
        jTextField13.setText(nic);
        jTextField14.setText(nic);
        jTextField15.setText(nic);
        jTextField16.setText(nic);
        jTextField17.setText(nic);
        jTextField18.setText(nic);
        
        jTextField19.setText(nic);
        jTextField20.setText(nic);
        jTextField21.setText(nic);
        jTextField22.setText(nic);
        jTextField23.setText(nic);
        jTextField24.setText(nic);
        jTextField25.setText(nic);
    }
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    if(jTextField1.getText().equals("")|| jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")||jTextField5.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null,"Nie wprowadzono wszystkich danych");
    }
    else{
        
        String marka,model,nr_vin,nr_rej,kier;
        boolean bt,oc;

        marka = jTextField1.getText();
        model = jTextField2.getText();
        nr_rej = jTextField3.getText();
        nr_vin = jTextField4.getText();
        kier=jTextField5.getText();
        bt = jCheckBox1.isEnabled();
        oc=  jCheckBox2.isEnabled();

        //String t=marka +" "+ model+" " +nr_vin+" "+nr_rej+" "+bt+" "+oc+" "+kier;
        //jTextArea1.setText(t);
        
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="insert into Pojazdy (Marka,Model,[Numer rejestracyjny], [Numer VIN], [Badanie techniczne], [Ubezpieczenie OC],ID_kierowcy) "
                    + "values ('"+marka+"','"+model+"','"+nr_rej+"','"+nr_vin+"','"+bt+"','"+oc+"','"+kier+"')";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jTextField6.getText().equals("")|| jTextField7.getText().equals("")||jTextField8.getText().equals("")||jTextField9.getText().equals("")||jTextField10.getText().equals("")||jTextField11.getText().equals("")||jTextField25.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null,"Nie wprowadzono wszystkich danych");
    }
    else{
            String imie,nazwisko, województwo,miasto,ulica,data_zatr,stawka;
            
            imie=jTextField6.getText();
            nazwisko=jTextField7.getText();
            województwo=jTextField8.getText();
            miasto=jTextField9.getText();
            ulica=jTextField10.getText();
            data_zatr=jTextField11.getText();
            stawka=jTextField25.getText();
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="insert into Kierowcy (Imie,Nazwisko,Województwo, Miasto, Ulica, [Data zatrudnienia],[Stawka godz nominalna]) "
                    + "values ('"+imie+"','"+nazwisko+"','"+województwo+"','"+miasto+"','"+ulica+"','"+data_zatr+"','"+stawka+"')";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jTextField12.getText().equals("")|| jTextField13.getText().equals("")||jTextField14.getText().equals("")||jTextField15.getText().equals("")||jTextField16.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null,"Nie wprowadzono wszystkich danych");
    }
    else{
            String id_kier,data_pocz, data_koniec,licznik_pocz,licznik_kon,id_trasy;
            
            id_kier=jTextField12.getText();
            data_pocz=jTextField13.getText();
            data_koniec=jTextField14.getText();
            licznik_pocz=jTextField15.getText();
            licznik_kon=jTextField16.getText();
            id_trasy=jTextField17.getText();
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="insert into Kursy (ID_kierowcy,[Data rozpoczęcia kursu],[Data zakończenia kursu], [Stan licznika początek], [Stan licznika koniec], ID_trasy) "
                    + "values ('"+id_kier+"','"+data_pocz+"','"+data_koniec+"','"+licznik_pocz+"','"+licznik_kon+"','"+id_trasy+"')";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       if(jTextField18.getText().equals("")|| jTextField19.getText().equals("")||jTextField20.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null,"Nie wprowadzono wszystkich danych");
    }
    else{
            String nazwa_trasy,czas_trasy,dlugosc_trasy;
            
            nazwa_trasy=jTextField18.getText();
            czas_trasy=jTextField19.getText();
            dlugosc_trasy=jTextField20.getText();
           
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="insert into Trasy ([Nazwa trasy],[Czas trasy],[Długość trasy]) "
                    + "values ('"+nazwa_trasy+"','"+czas_trasy+"','"+dlugosc_trasy+"')";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       if(jTextField21.getText().equals("")|| jTextField22.getText().equals("")||jTextField23.getText().equals("")||jTextField24.getText().equals(""))
    {
        JOptionPane.showMessageDialog(null,"Nie wprowadzono wszystkich danych");
    }
    else{
            String punkt,czas_trasy_t_1,dlugosc_trasy_t_1,id_trasy;
            
            punkt=jTextField21.getText();
            dlugosc_trasy_t_1=jTextField22.getText();
            czas_trasy_t_1=jTextField23.getText();
            id_trasy=jTextField24.getText();
           
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="insert into [Punkty pośrednie] (Punkt,[Odległość od poprzedniego punktu],[Czas przejazdu od poprzedniego punktu],ID_trasy) "
                    + "values ('"+punkt+"','"+dlugosc_trasy_t_1+"','"+czas_trasy_t_1+"','"+id_trasy+"')";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }      
    }//GEN-LAST:event_jButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        odswież_tab();
        jList1.setSelectedIndex(0);
    }//GEN-LAST:event_formWindowOpened
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int r=jTable1.getSelectedRow();
        int c=jTable1.getSelectedColumn();
        String t=jTable1.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość "+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_trasy");
        else{
        
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="delete from Pojazdy where ID_pojazdu="+t+"";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
        odswież_tab();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int r=jTable2.getSelectedRow();
        int c=jTable2.getSelectedColumn();
        String t=jTable2.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość "+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_kierowcy");
        else{
        
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="delete from Kierowcy where ID_kierowcy="+t+"";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
        odswież_tab();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int r=jTable3.getSelectedRow();
        int c=jTable3.getSelectedColumn();
        String t=jTable3.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość "+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_pojazdu");
        else{
        
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="delete from Kursy where ID_kursu="+t+"";
            
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
        odswież_tab();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int r=jTable5.getSelectedRow();
        int c=jTable5.getSelectedColumn();
        String t=jTable5.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość "+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_punkt");
        else{
        
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="delete from [Punkty pośrednie] where ID_punkt="+t+"";
            
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
        odswież_tab();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int r=jTable4.getSelectedRow();
        int c=jTable4.getSelectedColumn();
        String t=jTable4.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość "+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_trasy");
        else{
        
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
        //próba połączenia i wykoania zapytania        
        Connection con;
        try {
            String SQL ="delete from Trasy where ID_trasy="+t+"";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
        odswież_tab();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

    String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
    //próba połączenia i wykoania zapytania        
    Connection con;

    if(jList1.getSelectedIndex()==0)
        { 
        try {
            String SQL = jTextArea1.getText();

            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
    
    if(jList1.getSelectedIndex()==1)
        { 
        try {
            String SQL = "select imie+' '+nazwisko as 'Kierowca',marka+' '+model as 'Pojazd' \n" +
            "from Kierowcy k inner join Pojazdy p\n" +
            "on k.ID_kierowcy=p.ID_kierowcy\n" +
            "order by Nazwisko asc";

            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }}
        if(jList1.getSelectedIndex()==2)
        {
            try {
            String SQL = "select imie+' '+nazwisko as 'Osoba', datediff(MINUTE,[Data rozpoczęcia kursu],[Data zakończenia kursu] )\n" +
            "as 'Czas kursu rzeczywisty (min)',[Stan licznika koniec]-[Stan licznika początek] as 'Rzeczywista dług kursu (km)' from Kursy ku inner join Kierowcy ki\n" +
            "on ku.ID_kierowcy=ki.ID_kierowcy";

            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (SQLException e) {
            e.printStackTrace();
        }}
        if(jList1.getSelectedIndex()==3)
        {
            try {
            String SQL = "select [Nazwa trasy],sum([Odległość od poprzedniego punktu])as'całk odległ (km)',sum([Czas przejazdu od poprzedniego punktu]) as'całk czas (min)',\n" +
            "(sum([Odległość od poprzedniego punktu])/sum([Czas przejazdu od poprzedniego punktu])/60) as' śr predkosc (km/h)'\n" +
            "from Trasy t inner join [Punkty pośrednie] p\n" +
            "on t.ID_trasy=p.ID_trasy\n" +
            "group by  grouping sets ([Nazwa trasy])";

            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        }
        if(jList1.getSelectedIndex()==4)
        {
            int bonus = 100;
             try {
            String SQL = "select Nazwisko+' '+imie as'Kierowca',\n" +
"\n" +
"case when sum([Stan licznika koniec]-[Stan licznika początek])>100 then\n" +
"	(sum(([Stan licznika koniec]-[Stan licznika początek])+((DATEDIFF(MINUTE,[Data rozpoczęcia kursu],[Data zakończenia kursu])*[Stawka godz nominalna])/60))+"+bonus+")\n" +
"	else\n" +
"	sum(([Stan licznika koniec]-[Stan licznika początek])+((DATEDIFF(MINUTE,[Data rozpoczęcia kursu],[Data zakończenia kursu])*[Stawka godz nominalna])/60)) end as 'Pensja'\n" +
"from Kierowcy ki inner join Kursy ku \n" +
"on ki.ID_kierowcy=ku.ID_kierowcy\n" +
"\n" +
"group by grouping sets ((Nazwisko,imie))\n" +
"order by Nazwisko desc";

            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ResultSet rs=ps.executeQuery();
            jTable6.setModel(DbUtils.resultSetToTableModel(rs));
        }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int r=jTable2.getSelectedRow();
        int c=jTable2.getSelectedColumn();
        String t=jTable2.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość ID"+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_kierowcy");
        else
        {
            String imie,nazwisko, województwo,miasto,ulica,data_zatr,stawka;
            
            imie=jTable2.getValueAt(r,1 ).toString();
            nazwisko=jTable2.getValueAt(r,2 ).toString();
            województwo=jTable2.getValueAt(r,3 ).toString();
            miasto=jTable2.getValueAt(r,4 ).toString();
            ulica=jTable2.getValueAt(r,5 ).toString();
            data_zatr=jTable2.getValueAt(r,6 ).toString();
            stawka=jTable2.getValueAt(r,7 ).toString();
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
            //próba połączenia i wykoania zapytania        
            Connection con;
        try {
            String SQL ="update Kierowcy set imie='"+imie+"',nazwisko='"+nazwisko+"',województwo='"+województwo+"',miasto='"+miasto+"',ulica='"+ulica+"',[data zatrudnienia]='"+data_zatr+"',[Stawka godz nominalna]='"+stawka+"' where ID_kierowcy='"+t+"'";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int r=jTable1.getSelectedRow();
        int c=jTable1.getSelectedColumn();
        String t=jTable1.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość ID"+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_pojazdu");
        else
        {
            String marka,model, nr_rej,nr_vin,bt,oc,ID_kier;
            
            marka=jTable1.getValueAt(r,1 ).toString();
            model=jTable1.getValueAt(r,2 ).toString();
            nr_rej=jTable1.getValueAt(r,3 ).toString();
            nr_vin=jTable1.getValueAt(r,4 ).toString();
            bt=jTable1.getValueAt(r,5 ).toString();
            oc=jTable1.getValueAt(r,6 ).toString();
            ID_kier=jTable1.getValueAt(r,7 ).toString();
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
            //próba połączenia i wykoania zapytania        
            Connection con;
        try {
            String SQL ="update Pojazdy set marka='"+marka+"',model='"+model+"',[numer rejestracyjny]='"+nr_rej+"',[numer vin]='"+nr_vin+"',[badanie techniczne]='"+bt+"',[ubezpieczenie oc]='"+oc+"',ID_kierowcy='"+ID_kier+"' where ID_pojazdu='"+t+"'";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        int r=jTable4.getSelectedRow();
        int c=jTable4.getSelectedColumn();
        String t=jTable4.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość ID"+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_trasy");
        else
        {
            String nazwa_trasy,czas_trasy, długość;
            
            nazwa_trasy=jTable4.getValueAt(r,1 ).toString();
            czas_trasy=jTable4.getValueAt(r,2 ).toString();
            długość=jTable4.getValueAt(r,3 ).toString();
                       
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
            //próba połączenia i wykoania zapytania        
            Connection con;
        try {
            String SQL ="update Trasy set [nazwa trasy]='"+nazwa_trasy+"',[czas trasy]='"+czas_trasy+"',[długość trasy]='"+długość+"' where ID_trasy='"+t+"'";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        int r=jTable5.getSelectedRow();
        int c=jTable5.getSelectedColumn();
        String t=jTable5.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość ID"+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_punkt");
        else
        {
            String punkt,odle_t_1,czas_t_1,ID_trasy;
            
            punkt=jTable5.getValueAt(r,1 ).toString();
            odle_t_1=jTable5.getValueAt(r,2 ).toString();
            czas_t_1=jTable5.getValueAt(r,3 ).toString();
            ID_trasy=jTable5.getValueAt(r,4 ).toString();         
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
            //próba połączenia i wykoania zapytania        
            Connection con;
        try {
            String SQL ="update [punkty pośrednie] set punkt='"+punkt+"',[odległość od poprzedniego punktu]='"+odle_t_1+"',[czas przejazdu od poprzedniego punktu]='"+czas_t_1+"',ID_trasy='"+ID_trasy+"' where ID_punkt='"+t+"'";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }  
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        int r=jTable3.getSelectedRow();
        int c=jTable3.getSelectedColumn();
        String t=jTable3.getValueAt(r, c).toString();
        //jTextArea1.setText("Wartość ID"+t+" Wiersz "+r+" Kolumna "+c);
        
        if(r<0||c>=1)
            JOptionPane.showMessageDialog(null,"Upewnij się ,że wybrałeś wartość w wierszu X kolumny ID_kursu");
        else
        {
            String ID_kier,data_pocz,data_koniec,licznik_pocz,licznik_kon,ID_trasy;
            
            ID_kier=jTable3.getValueAt(r,1 ).toString();
            data_pocz=jTable3.getValueAt(r,2 ).toString();
            data_koniec=jTable3.getValueAt(r,3 ).toString();
            licznik_pocz=jTable3.getValueAt(r,4 ).toString();         
            licznik_kon=jTable3.getValueAt(r,5 ).toString();  
            ID_trasy=jTable3.getValueAt(r,6 ).toString();  
            
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Kier_Kurs;integratedSecurity=true";
            //próba połączenia i wykoania zapytania        
            Connection con;
        try {
            String SQL ="update Kursy set ID_kierowcy='"+ID_kier+"',[data rozpoczęcia kursu]='"+data_pocz+"',[data zakończenia kursu]='"+data_koniec+"',[Stan licznika początek]='"+licznik_pocz+"',[Stan licznika koniec]='"+licznik_kon+"',ID_trasy='"+ID_trasy+"' where ID_kursu='"+t+"'";
            
            con=DriverManager.getConnection(connectionUrl);        
            PreparedStatement ps;
            ps=con.prepareStatement(SQL);
            ps.execute();
            }
        // Handle any errors that may have occurred.
        catch (SQLException e) {
            e.printStackTrace();
        }
        odswież_tab();
        }  
    }//GEN-LAST:event_jButton17ActionPerformed

    public void toExcel(JTable table, File file){
		try{
			TableModel model = table.getModel();
			FileWriter excel = new FileWriter(file);

			for(int i = 0; i < model.getColumnCount(); i++){
				excel.write(model.getColumnName(i) + "\t");
			}

			excel.write("\n");

			for(int i=0; i< model.getRowCount(); i++) {
				for(int j=0; j < model.getColumnCount(); j++) {
					excel.write(model.getValueAt(i,j).toString()+"\t");
				}
				excel.write("\n");
			}

			excel.close();
		}catch(IOException e){ System.out.println(e); }
	}
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
{
                JFileChooser fc = new JFileChooser();
                int option = fc.showSaveDialog(jTable6);
                if(option == JFileChooser.APPROVE_OPTION){
                    String filename = fc.getSelectedFile().getName(); 
                    String path = fc.getSelectedFile().getParentFile().getPath();

					int len = filename.length();
					String ext = "";
					String file = "";

					if(len > 4){
						ext = filename.substring(len-4, len);
					}

					if(ext.equals(".xls")){
						file = path + "\\" + filename; 
					}else{
						file = path + "\\" + filename + ".xls"; 
					}
					toExcel(jTable6, new File(file));
				}
			} 
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
